server:
  port: 8080

spring:
  application:
    name: yx-circle

logging:
  level:
    root: info
    com.yx.circle: debug

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
